[project]
name = "auto-lgtm"
version = "0.1.0"
description = "Auto LGTM is a AI PR reviewer"
readme = "README.md"
requires-python = ">=3.12.6"
dependencies = [
    "loguru>=0.7.3",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "rich>=14.0.0",
    "pyfiglet>=0.8.post1"
]
